let StockProductos = [
    { id: 1,nombre: "TINTO-1", tipo: "tinto", desc: "...", precio: 800,}, 
    { id: 2,nombre: "TINTO-2", tipo: "tinto", desc: "...", precio: 800 },
    { id: 3,nombre: "TINTO-3", tipo: "tinto", desc: "...", precio: 800 },
    { id: 4,nombre: "TINTO-4", tipo: "tinto", desc: "...", precio: 1400 },
    { id: 5,nombre: "TINTO-5", tipo: "tinto", desc: "...", precio: 1500 },
    { id: 6,nombre: "TINTO-6", tipo: "tinto", desc: "...", precio: 3500 },
    { id: 7,nombre: "TINTO-7", tipo: "tinto", desc: "...", precio: 2800 },
    { id: 8,nombre: "TINTO-8", tipo: "tinto", desc: "...", precio: 1800 },
    { id: 9,nombre: "TINTO-9", tipo: "tinto", desc: "...", precio: 7000 },
    { id: 10,nombre: "TINTO-10", tipo: "tinto", desc: "...", precio: 5500 },
    { id: 11,nombre: "BLANCO-1", tipo: "blanco ", desc: "...", precio: 1200 },
    { id: 12,nombre: "BLANCO-2", tipo: "blanco", desc: "...", precio: 2200 },
    { id: 13,nombre: "BLANCO-3", tipo: "blanco", desc: "...", precio: 2500 },
    { id: 14,nombre: "BLANCO-4", tipo: "blanco", desc: "...", precio: 1800 },
    { id: 15,nombre: "BLANCO-5", tipo: "blanco", desc: "...", precio: 3000 },
    { id: 16,nombre: "BLANCO-6", tipo: "blanco", desc: "...", precio: 1250 },
    { id: 17,nombre: "ESPUMANTE-1", tipo: "espumante", desc: "...", precio: 1500 },
    { id: 18,nombre: "ESPUMANTE-2", tipo: "espumante", desc: "...", precio: 5000 },
    { id: 19,nombre: "ESPUMANTE-3", tipo: "espumante", desc: "...", precio: 2500 },
    { id: 20,nombre: "ESPUMANTE-4", tipo: "espumante", desc: "...", precio: 7000 },
    { id: 21,nombre: "ROSADO-1", tipo: "rosado", desc: "...", precio: 3000 },
    { id: 22,nombre: "ROSADO-2", tipo: "rosado", desc: "...", precio: 2000 },
    { id: 23,nombre: "ROSADO-3", tipo: "rosado", desc: "...", precio: 1500 },
    { id: 24,nombre: "ROSADO-4", tipo: "rosado", desc: "...", precio: 1200 },
    { id: 25,nombre: "ROSADO-5", tipo: "rosado", desc: "...", precio: 2200 },
]